name: Build and tag

on:
  push:
    branches:
      - main # Default release branch
    tags:
      - "!*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        env:
          NODE_ENV: production
        run: npm run build

      - name: Get version 
        uses: bbonkr/get-version-action@v1.0.1
        id: get_version
        with:
          project: ./package.json

      - name: Check git tag 
        uses: bbonkr/git-tag-check-action@v1.0.7
        id: git_tag_check
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          tag: 'v${{ steps.get_version.outputs.version }}'

      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        if: ${{ steps.git_tag_check.outputs.tag == '' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ steps.get_version.outputs.version }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

      - name: Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        if: ${{ steps.git_tag_check.outputs.tag == '' }}
        with:
          config-name: release-drafter.yml
          version: ${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
