name: Verify to Build 

on:
  pull_request:

jobs:
  verify-build:
    name: Verify to build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        env:
          NODE_ENV: production
        run: npm run build
